export const URL = 'http://magento.softwaretestingboard.com/';
export const homePageSignInLink = '.panel > .header > .authorization-link > a';
export const userNameField = '#email';
export const passwordField = '#pass';
export const loginBtn      = '#send2';
export const welcomeMsg    =  ':nth-child(2) > .greet > .logged-in';
export const createAccountLink = '.panel > .header > :nth-child(3) > a';
export const firstnameField = '#firstname';
export const lastnameField = '#lastname';
export const newAccemail = '#email_address'
export const newAccpasswordField = '#password';
export const confirmpasswordField = '#password-confirmation';
export const createAccBtn = '#form-validate > .actions-toolbar > div.primary > .action > span';
export const menTab = '#ui-id-5 > :nth-child(2)';
export const menTops = 'dd > .items > :nth-child(1) > a';
export const menJackets = '.categories-menu > :nth-child(2) > :nth-child(2) > a';
export const yellowJacket = ':nth-child(1) > .product-item-info > .photo > .product-image-container > .product-image-wrapper > .product-image-photo';
export const sizeJacket = '#option-label-size-143-item-170';
export const colourJacket = '#option-label-color-93-item-49';
export const qtyJacket = '#qty'
export const addcartBtn = '#product-addtocart-button > span';
//export const addcartMsg = '.message-success > div';
//export const addcartQty = '#cart-item-305517-qty';
//export const showCart = '.showcart';
//export const addcartAmount = '.amount > .price-wrapper > .price';
//export const proceedCheckout = '#top-cart-btn-checkout';